### ISSUE TITLE
How to run stylize.py

### ISSUE THREAD

**Issue by williamzrj** [iamRusty/fast-neural-style-pytorch#13]
I don't know where to put the address （--content_dir )

**Comment by rrmina** [comment]
Hi. There's no `--content_dir` argument in the repo. Did you mean to ask for the path of the content image?

**Comment by williamzrj** [comment]
yes

**Comment by rrmina** [comment]
First, please change [**line 9**](https://github.com/rrmina/fast-neural-style-pytorch/blob/master/stylize.py#L9) from

`STYLE_TRANSFORM_PATH = "transforms/udnie_aggressive.pth"`

to

`STYLE_TRANSFORM_PATH = "transforms/udnie.pth"` 

or to any style that you want and is available in the transforms folder

Then, uncomment [**line 135**](https://github.com/rrmina/fast-neural-style-pytorch/blob/master/stylize.py#L135) and run the script by `python stylize.py`

The script will ask for the content image path while it is running. As an example, you may type `images/tokyo2.jpg`
