### ISSUE TITLE
Train Notebook: Request for Improvements

### ISSUE THREAD

**Issue by rrmina** [iamRusty/fast-neural-style-pytorch#3]
This still needs a lot of changes to make it a **one-click-run-all** interface.
Some of the changes requested are:

- First cell should contain **all** of the wheel installations **and**
- First cell should also download all of the required local files (e.g. image file)
- There should be separate cells for hyperparameter (global settings) and imports
- Images should be displayed every `show_iter`
- A link directing to Google Colab is also welcome. It is most likely placed on top (1st markdown cell) of the notebook. 

This [notebook](https://github.com/iamRusty/neural-style-pytorch/blob/master/neural_style.ipynb) can be used a reference for the first 4 bullets. Can you do it @p-rit ?

**Comment by p-rit** [comment]
Will try to improve

**Comment by p-rit** [comment]
link directing to google colab notebook containing improved code

https://colab.research.google.com/drive/1lL81ANjjehOAudXy6CHNUHmQ9aFdJvLg#scrollTo=KhEWjKxMb0oO

**Comment by rrmina** [comment]
Hi @p-rit . Thank you improving the notebook. Some comments:
* Before moving on to downloading the models, go back to the content directory (i.e. `%cd ..`)
* Edit the lines downloading the helper codes and style image. The current notebook downloads the html files, instead of the raw files that the links are pointing to. 
e.g. instead of 
```
instead of 

!wget https://github.com/iamRusty/fast-neural-style-pytorch/blob/master/transformer.py

do

!wget https://raw.githubusercontent.com/iamRusty/fast-neural-style-pytorch/master/transformer.py
```
* You don't need to put the cell containing itot, ttoi, etc. `utils.py` already has the more updated version of the helper codes. So yeah, you may **delete** that cell.

* Lastly, display the image after saving the sample image. You may use:
```
utils.show(sample_image)
```

Edit: One more thing, there's a typo with the import of the `models` from `torchvision`
Edit2: **Also, change the content weight and style weight to `2e-6` and `50` respectively. The current settings were used for udnie, not mosaic. the mosaic style needs more weight on content :)**
