### ISSUE TITLE
new style image

### ISSUE THREAD

**Issue by hyunmj** [iamRusty/fast-neural-style-pytorch#8]
Hello
Thank you for sharing your source codes. 
I want use my own style image when training network. 
Could you tell me how i can do this?

**Comment by rrmina** [comment]
Hi @hyunmj!

1. Download the whole repository
2. Edit line 17 of [train.py](https://github.com/rrmina/fast-neural-style-pytorch/blob/master/train.py) with the location of your own style image.
3. [Run train.py script](https://github.com/rrmina/fast-neural-style-pytorch#training-style-transformation-network)

Alternatively, you can [fork a notebook](https://nbviewer.jupyter.org/github/rrmina/fast-neural-style-pytorch/blob/master/notebook/mosaic_TransformerNetwork.ipynb) and run your training in [google colab](https://colab.research.google.com/).

Good luck!

**Comment by hyunmj** [comment]
thank you very much😊😀
